version: '3'
services:
  mongo:
    image: mongo:3.6
  web:
    build: .
    ports:
     - "8080:8080"
    environment:
     - MONGODB_URI=mongodb://mongo:27017/test
    links:
     - mongo 
     - productdb
    depends_on: 
     - mongo 
     - productdb
    volumes:
     - .:/starter
     - /starter/node_modules
     